### ISSUE TITLE
Order is not deterministic

### ISSUE THREAD

**Issue by markusheiden** [sl1pm4t/k2tf#61] opened 2020-03-11 12:45 UTC
The order of "cpu" and "memory" in the following snippet is non-deterministic when generated from the same yaml.

```
container {
  resources {
    limits {
      cpu    = "250m"
      memory = "50Mi"
    }
  }
}
```

**Comment by sl1pm4t** [comment] 2021-10-05 03:25
Hi @markusheiden - I'm not able to reproduce this problem. I suspect it did exist at one point but has been fixed by an upstream change in HashiCorp libraries. I'm going to close, but if you can reproduce let me know.

**Closed by sl1pm4t** 2021-10-05 03:25 UTC
